
'use strict';
// S.3 greybox core: world-space simulation. Deliberately contains no lanes, horizon, road, or gates.
const canvas=document.querySelector('#game'), ctx=canvas.getContext('2d');
const VIEW={w:540,h:960}, WORLD={halfW:810,halfH:1440,maxEnemies:220}, CAMERA={deadZone:.15}; let dpr=1;
function resize(){dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);VIEW.w=innerWidth;VIEW.h=innerHeight} addEventListener('resize',resize);resize();
const keys=new Set(), pointer={active:false,x:0,y:0};
// Virtual thumbstick (owner request 2026-08-03: "put the virtual joystick at the bottom centre
// so a person can use their thumb"). The old scheme steered by the finger's offset from the
// SCREEN CENTRE, which forced you to hold your thumb over the middle of the display — right on
// top of the player sprite — to move accurately.
// Now the stick FLOATS: it anchors wherever the thumb lands, and when idle it rests at the
// bottom-centre home position so it reads as a real control, not an invisible gesture.
const STICK={home:{x:0,y:0},base:{x:0,y:0},knob:{x:0,y:0},radius:78,dead:0.16,active:false,dx:0,dy:0};
function stickHome(){STICK.home.x=VIEW.w/2;STICK.home.y=VIEW.h-Math.min(150,VIEW.h*0.22);}
function stickSet(x,y){let dx=x-STICK.base.x,dy=y-STICK.base.y,d=Math.hypot(dx,dy);
  if(d>STICK.radius){dx*=STICK.radius/d;dy*=STICK.radius/d;d=STICK.radius}
  STICK.knob.x=STICK.base.x+dx;STICK.knob.y=STICK.base.y+dy;
  // Dead zone stops a resting thumb from creeping the player around.
  let n=d/STICK.radius;if(n<STICK.dead){STICK.dx=STICK.dy=0;return}
  STICK.dx=dx/(d||1);STICK.dy=dy/(d||1);}
function stickRelease(){STICK.active=false;STICK.dx=STICK.dy=0;stickHome();STICK.base.x=STICK.home.x;STICK.base.y=STICK.home.y;STICK.knob.x=STICK.base.x;STICK.knob.y=STICK.base.y;}
stickRelease();addEventListener('resize',stickRelease);

addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('pointerdown',e=>{pointer.active=true;pointer.x=e.clientX;pointer.y=e.clientY;canvas.setPointerCapture(e.pointerId);STICK.active=true;STICK.base.x=e.clientX;STICK.base.y=e.clientY;stickSet(e.clientX,e.clientY)});canvas.addEventListener('pointermove',e=>{if(pointer.active){pointer.x=e.clientX;pointer.y=e.clientY;if(STICK.active)stickSet(e.clientX,e.clientY)}});canvas.addEventListener('pointerup',()=>{pointer.active=false;stickRelease()});canvas.addEventListener('pointercancel',()=>{pointer.active=false;stickRelease()});
const FORGE_KEY='hive_swarm_forge_values_v1', copy=o=>JSON.parse(JSON.stringify(o));
const META_KEY='hive_swarm_meta_v1';let META=(()=>{try{return Object.assign({credits:0,damage:0,hp:0,speed:0},JSON.parse(localStorage.getItem(META_KEY)||'{}'))}catch(_){return {credits:0,damage:0,hp:0,speed:0}}})();function saveMeta(){try{localStorage.setItem(META_KEY,JSON.stringify(META))}catch(_){}}
const FORGE_BASE={player:{speed:245,maxHp:100,pickupRadius:90},world:{halfW:810,halfH:1440,maxEnemies:220,deadZone:.15},waves:{seconds:30,baseInterval:.68,intervalPerWave:.034},drops:{xp:1,metaChance:.08,healChance:.07,heal:12},weapons:[{id:'weapon.pulse',name:'Pulse Carbine',damage:17,rate:.18,speed:720,shots:1,pierce:1,color:'#b7fff5',range:760}],entities:[{id:'enemy.shambler',name:'Shambler',r:16,hp:28,speed:72,damage:8,color:'#9ab0b4',weight:7,dropXp:1,unlockWave:1,sprite:'art_src/topdown_v1/shambler.png'},{id:'enemy.runner',name:'Runner',r:14,hp:17,speed:128,damage:6,color:'#e97088',weight:4,dropXp:1,unlockWave:4,sprite:'art_src/topdown_v1/runner.png'},{id:'enemy.crawler',name:'Crawler',r:15,hp:38,speed:96,damage:10,color:'#b5bd76',weight:3,dropXp:2,unlockWave:5,sprite:'art_src/topdown_v1/crawler.png'},{id:'enemy.necroNode',name:'Necro Node',r:23,hp:140,speed:0,damage:8,color:'#a46fca',weight:1,dropXp:5,unlockWave:6,sprite:'art_src/topdown_v1/necro_node.png'},{id:'enemy.brute',name:'Brute',r:24,hp:95,speed:42,damage:16,color:'#e5a66e',weight:2,dropXp:3,unlockWave:8,sprite:'art_src/topdown_v1/brute.png'},{id:'enemy.armored',name:'Armored Dead',r:20,hp:120,speed:54,damage:14,color:'#71889b',weight:2,dropXp:4,unlockWave:9,sprite:'art_src/topdown_v1/armored_dead.png'},{id:'enemy.mutant',name:'Mutant Enforcer',r:21,hp:175,speed:68,damage:20,color:'#d86c67',weight:1,dropXp:7,unlockWave:13,sprite:'art_src/topdown_v1/mutant_enforcer.png'},{id:'enemy.colossus',name:'Zombie Colossus',r:42,hp:1200,speed:32,damage:35,color:'#8b765f',weight:1,dropXp:20,unlockWave:10,sprite:'art_src/topdown_v1/zombie_colossus.png'}]};
function forgeMerge(base,saved){let next=copy(base);if(!saved||typeof saved!=='object')return next;for(const key of Object.keys(base)){if(Array.isArray(base[key])&&Array.isArray(saved[key])){let shipped=new Map(base[key].map(row=>[row.id,row]));next[key]=saved[key].map(row=>Object.assign({},shipped.get(row.id)||{},row));for(const row of base[key])if(!saved[key].some(x=>x.id===row.id))next[key].push(copy(row))}else if(saved[key]&&typeof saved[key]==='object')Object.assign(next[key],saved[key])}return next}
let EDIT=forgeMerge(FORGE_BASE,(()=>{try{return JSON.parse(localStorage.getItem(FORGE_KEY)||'null')}catch(_){return null}})());
Object.assign(EDIT.waves,{budgetBase:EDIT.waves.budgetBase??4,budgetExponent:EDIT.waves.budgetExponent??1.11});
function persistForge(){try{localStorage.setItem(FORGE_KEY,JSON.stringify(EDIT))}catch(_){alert('Storage full — Forge values were not saved.')}}
const SPRITES={};function spriteFor(src){if(!src)return null;if(!SPRITES[src]){let image=new Image();image.src=src;SPRITES[src]=image}return SPRITES[src]}
const SFX={fire:'assets/SFX/m41a-pulse-rifle.mp3',hit:'assets/SFX/xeno attack.mp3',kill:'assets/SFX/xenotera hit.mp3'};let audioOn=true;function sfx(name,vol=.25){if(!audioOn||!SFX[name]||typeof Audio==='undefined')return;let a=new Audio(SFX[name]);a.volume=vol;a.play().catch(()=>{})}
let player={x:0,y:0,r:16,hp:100,maxHp:100,speed:245,pickupRadius:90,inv:0,angle:0};
let orbsCollected=0;
let cam={x:0,y:0}, enemies=[], bullets=[], particles=[], pickups=[], elapsed=0, score=0, wave=1,spawnBudget=0, fireClock=0, shake=0, state='title',xp=0,level=1,nextXp=8,choices=[],cardPicks=0,excessThreat=0,evolved=false,heldWeapons=[];
let WEAPON,ENEMIES;function applyForge(){Object.assign(WORLD,EDIT.world);CAMERA.deadZone=EDIT.world.deadZone;Object.assign(player,{speed:EDIT.player.speed,maxHp:EDIT.player.maxHp,pickupRadius:EDIT.player.pickupRadius});WEAPON=EDIT.weapons[0];ENEMIES=EDIT.entities}applyForge();
function reset(){applyForge();heldWeapons=[copy(WEAPON)];WEAPON=heldWeapons[0];player.speed=Math.round(player.speed*(1+Math.min(.25,META.speed*.05)));player.maxHp=Math.round(player.maxHp*(1+Math.min(.25,META.hp*.05)));Object.assign(player,{x:0,y:0,hp:player.maxHp,inv:0,angle:0});cam={x:0,y:0};enemies=[];bullets=[];particles=[];pickups=[];elapsed=score=wave=spawnBudget=fireClock=shake=xp=cardPicks=orbsCollected=0;evolved=false;level=1;nextXp=8;state='play'}
function rand(a,b){return a+Math.random()*(b-a)} function dist2(a,b){let x=a.x-b.x,y=a.y-b.y;return x*x+y*y}
function spawnEnemy(){if(enemies.length>=WORLD.maxEnemies){excessThreat++;return}let a=Math.random()<.6?player.angle+rand(-Math.PI/3,Math.PI/3):Math.random()*Math.PI*2,distance=Math.hypot(VIEW.w,VIEW.h)*.72+rand(60,180),level=1+Math.floor(elapsed/EDIT.waves.seconds),roster=ENEMIES.filter(e=>(e.unlockWave||1)<=level),total=roster.reduce((n,e)=>n+Math.max(0,e.weight||0),0),roll=Math.random()*total,type=roster[0],boost=1+Math.min(.8,excessThreat*.04);for(const e of roster){roll-=Math.max(0,e.weight||0);if(roll<=0){type=e;break}}excessThreat=Math.max(0,excessThreat-1);let x=Math.max(-WORLD.halfW+type.r,Math.min(WORLD.halfW-type.r,player.x+Math.cos(a)*distance)),y=Math.max(-WORLD.halfH+type.r,Math.min(WORLD.halfH-type.r,player.y+Math.sin(a)*distance));enemies.push({x,y,r:type.r,hp:type.hp*(1+level*.13)*boost,maxHp:type.hp*(1+level*.13)*boost,speed:type.speed*(1+level*.025),damage:type.damage*boost,type,color:type.color,hit:0});}
function fire(){let target=null,best=Infinity;for(const e of enemies){let d=dist2(player,e);if(d<best){best=d;target=e}}if(!target)return;let a=Math.atan2(target.y-player.y,target.x-player.x);player.angle=a;for(const w of heldWeapons){sfx('fire',.08);for(let i=0;i<w.shots;i++){let spread=(i-(w.shots-1)/2)*.1;bullets.push({x:player.x+Math.cos(a+spread)*20,y:player.y+Math.sin(a+spread)*20,vx:Math.cos(a+spread)*w.speed,vy:Math.sin(a+spread)*w.speed,r:4,damage:w.damage*(1+Math.min(.25,META.damage*.05)),pierce:w.pierce,life:1.05})}}}
function burst(x,y,color,n=8){for(let i=0;i<n;i++){let a=Math.random()*6.283,s=rand(25,140);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.25,.55),color})}}
function followCamera(){let dx=player.x-cam.x,dy=player.y-cam.y,deadX=VIEW.w*CAMERA.deadZone,deadY=VIEW.h*CAMERA.deadZone;if(Math.abs(dx)>deadX)cam.x+=dx-Math.sign(dx)*deadX;if(Math.abs(dy)>deadY)cam.y+=dy-Math.sign(dy)*deadY;cam.x=Math.max(-WORLD.halfW+VIEW.w/2,Math.min(WORLD.halfW-VIEW.w/2,cam.x));cam.y=Math.max(-WORLD.halfH+VIEW.h/2,Math.min(WORLD.halfH-VIEW.h/2,cam.y));}
function update(dt){if(state!=='play')return;elapsed+=dt;wave=1+Math.floor(elapsed/EDIT.waves.seconds);player.inv=Math.max(0,player.inv-dt);let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(STICK.active&&(STICK.dx||STICK.dy)){dx=STICK.dx;dy=STICK.dy}let mag=Math.hypot(dx,dy);if(mag){player.x+=dx/mag*player.speed*dt;player.y+=dy/mag*player.speed*dt;player.angle=Math.atan2(dy,dx)}player.x=Math.max(-WORLD.halfW+player.r,Math.min(WORLD.halfW-player.r,player.x));player.y=Math.max(-WORLD.halfH+player.r,Math.min(WORLD.halfH-player.r,player.y));followCamera();
spawnBudget+=dt*EDIT.waves.budgetBase*Math.pow(EDIT.waves.budgetExponent,wave);while(spawnBudget>=1){spawnBudget-=1;spawnEnemy()}fireClock-=dt;if(fireClock<=0){fireClock+=WEAPON.rate;fire()}
for(let i=enemies.length-1;i>=0;i--){let e=enemies[i],vx=player.x-e.x,vy=player.y-e.y,d=Math.hypot(vx,vy)||1;e.x+=vx/d*e.speed*dt;e.y+=vy/d*e.speed*dt;for(let j=0;j<i;j++){let o=enemies[j],sx=e.x-o.x,sy=e.y-o.y,sd=Math.hypot(sx,sy)||.01,gap=(e.r+o.r)*.8;if(sd<gap){let push=(gap-sd)*.5;e.x+=sx/sd*push;e.y+=sy/sd*push;o.x-=sx/sd*push;o.y-=sy/sd*push}}e.hit=Math.max(0,e.hit-dt);if(d<e.r+player.r){if(!player.inv){player.hp-=e.damage;player.inv=.45;shake=8;burst(player.x,player.y,'#ff718a',14);if(player.hp<=0){player.hp=0;state='dead'}}e.x-=vx/d*20;e.y-=vy/d*20}}
for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let removed=b.life<=0;for(let j=enemies.length-1;j>=0&&!removed;j--){let e=enemies[j],r=e.r+b.r;if((e.x-b.x)**2+(e.y-b.y)**2<r*r){e.hp-=b.damage;e.hit=.1;sfx('hit',.08);burst(b.x,b.y,WEAPON.color,3);b.pierce--;if(e.hp<=0){score+=10;sfx('kill',.18);if((e.type.dropXp||0)>=5){META.credits++;saveMeta()}pickups.push({x:e.x,y:e.y,value:(e.type.dropXp||1)*EDIT.drops.xp});
              // Red health drop. Rarer than XP and only worth grabbing when hurt, so it reads as a
              // real decision rather than free healing. FORGE knob: drops.healChance / drops.heal.
              if(rand(0,1)<(EDIT.drops.healChance!==undefined?EDIT.drops.healChance:.07))
                pickups.push({x:e.x+rand(-14,14),y:e.y+rand(-14,14),heal:1,value:EDIT.drops.heal||12});burst(e.x,e.y,e.color,12);enemies.splice(j,1)}if(b.pierce<0)removed=true}}if(removed)bullets.splice(i,1)}
// XP orbs (owner request 2026-08-03: "no visual item collects that magnet would be for").
// pickupRadius is the MAGNET reach: inside it the orb accelerates toward the player and is
// visibly sucked in; it only banks once it actually touches you, so the magnet upgrade reads
// as a longer, more dramatic pull rather than a silent instant grab.
for(let i=pickups.length-1;i>=0;i--){let p=pickups[i],dx=player.x-p.x,dy=player.y-p.y,d=Math.hypot(dx,dy)||1;
  p.t=(p.t||0)+dt;p.vx=p.vx||0;p.vy=p.vy||0;
  if(d<player.pickupRadius){
    // Accelerate toward the player AND bleed off the sideways (tangential) component. Pure
    // attraction is orbital mechanics: an off-centre orb builds tangential speed, misses, and
    // circles forever. Damping the tangent is what guarantees it actually lands.
    let ux=dx/d,uy=dy/d,pull=520*(1-d/player.pickupRadius)+180;
    p.vx+=ux*pull*dt;p.vy+=uy*pull*dt;
    let tang=-p.vx*uy+p.vy*ux, damp=Math.min(1,6*dt);       // velocity component across the pull axis
    p.vx+=uy*tang*damp;p.vy-=ux*tang*damp;
    // Final approach: steer straight in so nothing can orbit at point-blank range.
    if(d<player.r+42){let sp=Math.max(340,Math.hypot(p.vx,p.vy));p.vx=ux*sp;p.vy=uy*sp}
    p.pulled=1;
    p.trail=p.trail||[];p.trail.push(p.x,p.y);if(p.trail.length>10)p.trail.splice(0,2);
  }
  else{p.vx*=Math.pow(.02,dt);p.vy*=Math.pow(.02,dt);p.pulled=0;if(p.trail)p.trail.length=0}
  p.x+=p.vx*dt;p.y+=p.vy*dt;
  if(d<player.r+10){
    if(p.heal){player.hp=Math.min(player.maxHp,player.hp+p.value);burst(p.x,p.y,'#ff5f7a',7)}
    else{xp+=p.value;orbsCollected++;burst(p.x,p.y,'#6fffe2',5)}
    sfx('hit',.05);pickups.splice(i,1);
    if(!p.heal&&xp>=nextXp){xp-=nextXp;level++;nextXp=Math.ceil(nextXp*1.35);state='levelup';offerCards()}}}
for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1)}shake=Math.max(0,shake-dt*25)}
function sx(x){return x-cam.x+VIEW.w/2}function sy(y){return y-cam.y+VIEW.h/2}
// QA probe. Playwright's evaluate() runs in its own context and cannot see script-scoped `let`
// declarations, so anything a test needs to assert has to be published on `window` explicitly.
window.__swarmDbg=()=>({state,wave,elapsed,score,level,xp,nextXp,orbsCollected,
  pickups:pickups.length,enemies:enemies.length,hp:player.hp,px:Math.round(player.x),py:Math.round(player.y),
  stick:{active:STICK.active,dx:Math.round(STICK.dx*100)/100,dy:Math.round(STICK.dy*100)/100,
         baseX:Math.round(STICK.base.x),baseY:Math.round(STICK.base.y),homeX:Math.round(STICK.home.x),homeY:Math.round(STICK.home.y)}});
function draw(){ctx.fillStyle='#091014';ctx.fillRect(0,0,VIEW.w,VIEW.h);let ox=rand(-shake,shake),oy=rand(-shake,shake);ctx.save();ctx.translate(ox,oy);ctx.strokeStyle='#142329';ctx.lineWidth=1;let grid=80,startX=(-cam.x%grid+grid)%grid,startY=(-cam.y%grid+grid)%grid;for(let x=startX;x<VIEW.w;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,VIEW.h);ctx.stroke()}for(let y=startY;y<VIEW.h;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(VIEW.w,y);ctx.stroke()}
for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.color;ctx.fillRect(sx(p.x)-2,sy(p.y)-2,4,4)}ctx.globalAlpha=1;for(const b of bullets){ctx.fillStyle=WEAPON.color;ctx.shadowColor=WEAPON.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(sx(b.x),sy(b.y),b.r,0,7);ctx.fill()}ctx.shadowBlur=0;
for(const p of pickups){let x=sx(p.x),y=sy(p.y),bob=Math.sin((p.t||0)*6)*1.6,
    r=p.heal?6:4+Math.min(3,(p.value||1)*.5),
    col=p.heal?'#ff5f7a':'#8ffff0',glow=p.heal?'#ff2d55':'#6fffe2';
  ctx.save();
  // Motion trail while the magnet has hold of it — the pull should be legible at a glance.
  if(p.pulled&&p.trail&&p.trail.length>3){ctx.strokeStyle=glow;ctx.lineWidth=r*.9;ctx.lineCap='round';
    for(let k=0;k<p.trail.length-2;k+=2){ctx.globalAlpha=.06+.5*(k/p.trail.length);
      ctx.beginPath();ctx.moveTo(sx(p.trail[k]),sy(p.trail[k+1]));ctx.lineTo(sx(p.trail[k+2]),sy(p.trail[k+3]));ctx.stroke()}
    ctx.globalAlpha=1}
  ctx.shadowColor=glow;ctx.shadowBlur=p.pulled?18:10;ctx.fillStyle=col;
  ctx.beginPath();ctx.arc(x,y+bob,r,0,7);ctx.fill();
  if(p.heal){ctx.fillStyle='#fff';ctx.fillRect(x-1.4,y+bob-4,2.8,8);ctx.fillRect(x-4,y+bob-1.4,8,2.8)}
  ctx.globalAlpha=.35;ctx.strokeStyle=glow;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y+bob,r+3,0,7);ctx.stroke();ctx.restore()}
for(const e of enemies){let x=sx(e.x),y=sy(e.y),img=spriteFor(e.type.sprite);if(img&&img.complete&&img.naturalWidth){let s=e.r*2.7;ctx.globalAlpha=e.hit?.72:1;ctx.drawImage(img,x-s/2,y-s/2,s,s);ctx.globalAlpha=1}else{ctx.fillStyle=e.hit?'#fff':e.color;ctx.beginPath();ctx.arc(x,y,e.r,0,7);ctx.fill()}ctx.fillStyle='#152025';ctx.fillRect(x-e.r,y-e.r-8,e.r*2,3);ctx.fillStyle='#8aff9b';ctx.fillRect(x-e.r,y-e.r-8,e.r*2*(e.hp/e.maxHp),3)}
let px=sx(player.x),py=sy(player.y);ctx.save();ctx.translate(px,py);ctx.rotate(player.angle);ctx.fillStyle=player.inv?'#ffffff':'#6fffe2';ctx.beginPath();ctx.arc(0,0,player.r,0,7);ctx.fill();ctx.fillStyle='#dff';ctx.fillRect(8,-4,22,8);ctx.restore();ctx.restore();
ctx.fillStyle='#dce9e7';ctx.font='700 16px system-ui';ctx.fillText('HiVE SWARM  ·  WAVE '+wave,18,32);ctx.font='14px system-ui';ctx.fillStyle='#a5c3be';ctx.fillText('SURVIVAL '+formatTime(elapsed)+'   SCORE '+score+'   HOSTILES '+enemies.length,18,55);ctx.fillStyle='#26383a';ctx.fillRect(18,70,180,10);ctx.fillStyle=player.hp>30?'#64e7b5':'#ff718a';ctx.fillRect(18,70,180*player.hp/player.maxHp,10);ctx.fillStyle='#dce9e7';ctx.fillText('HP '+Math.ceil(player.hp)+' / '+player.maxHp,205,80);
// XP / level readout — the orbs are now visible, so the counter they feed has to be too.
ctx.fillStyle='#1b2f33';ctx.fillRect(18,88,180,8);ctx.fillStyle='#6fffe2';ctx.fillRect(18,88,180*Math.max(0,Math.min(1,xp/nextXp)),8);
ctx.fillStyle='#9fded2';ctx.font='13px system-ui';ctx.fillText('LVL '+level+'   XP '+Math.floor(xp)+' / '+nextXp+'   ◆ '+orbsCollected,205,96);
// Thumbstick. Drawn at its resting home until a thumb grabs it, then wherever that thumb landed.
if(state==='play'){let bx=STICK.active?STICK.base.x:STICK.home.x,by=STICK.active?STICK.base.y:STICK.home.y,
  kx=STICK.active?STICK.knob.x:bx,ky=STICK.active?STICK.knob.y:by;
  ctx.save();ctx.globalAlpha=STICK.active?.34:.16;ctx.strokeStyle='#6fffe2';ctx.lineWidth=2;
  ctx.beginPath();ctx.arc(bx,by,STICK.radius,0,7);ctx.stroke();
  ctx.globalAlpha=STICK.active?.5:.22;ctx.fillStyle='#6fffe2';ctx.beginPath();ctx.arc(kx,ky,26,0,7);ctx.fill();ctx.restore()}
if(state==='title'||state==='dead'){ctx.fillStyle='rgba(3,8,10,.72)';ctx.fillRect(0,0,VIEW.w,VIEW.h);ctx.textAlign='center';ctx.fillStyle='#e4fff8';ctx.font='700 34px system-ui';ctx.fillText(state==='dead'?'RUN ENDED':'HiVE SWARM',VIEW.w/2,VIEW.h/2-24);ctx.save();ctx.font='12px system-ui';ctx.fillStyle='rgba(150,200,190,.55)';ctx.fillText('v1.2-alpha',VIEW.w/2,VIEW.h/2-5);ctx.restore();ctx.font='16px system-ui';ctx.fillStyle='#b3cbc7';ctx.fillText(state==='dead'?'Score '+score+' · survived '+formatTime(elapsed):'Open arena survival greybox',VIEW.w/2,VIEW.h/2+10);ctx.fillStyle='#6fffe2';ctx.fillText('Click or press Enter to deploy',VIEW.w/2,VIEW.h/2+50);ctx.textAlign='left'}}
function formatTime(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')} addEventListener('keydown',e=>{if(e.key==='Enter'&&(state==='title'||state==='dead'))reset()});canvas.addEventListener('click',()=>{if(state==='title'||state==='dead')reset()});
let last=performance.now(),accumulator=0;function frame(now){accumulator+=Math.min(.05,(now-last)/1000);last=now;while(accumulator>=1/60){update(1/60);accumulator-=1/60}draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.__hiveSwarmDebug=()=>({state,elapsed,score,wave,enemies:enemies.length,heldWeapons:heldWeapons.length,player:{x:player.x,y:player.y,hp:player.hp},camera:cam});
function offerCards(){let weapons=[{name:'Pulse Overdrive',text:'+25% Pulse damage',apply:()=>WEAPON.damage=Math.round(WEAPON.damage*1.25)},{name:'Scatter Shot',text:'New spread weapon: +2 bolts',apply:()=>WEAPON.shots=Math.min(5,WEAPON.shots+2)},{name:'Piercing Rounds',text:'+1 projectile pierce',apply:()=>WEAPON.pierce++}],stats=[{name:'Fleet Footed',text:'+12% movement speed',apply:()=>player.speed=Math.round(player.speed*1.12)},{name:'Reinforced',text:'+25 max HP and heal',apply:()=>{player.maxHp+=25;player.hp=Math.min(player.maxHp,player.hp+25)}},{name:'Magnet',text:'+45 pickup radius',apply:()=>player.pickupRadius+=45}],evo={name:'Plasma Evolution',text:'Wave 10 evolution: double pulse damage',apply:()=>{WEAPON.damage*=2;evolved=true}};let pool=[...weapons,...stats,...(wave>=10&&!evolved?[evo]:[])],first=cardPicks<3?weapons[Math.floor(Math.random()*weapons.length)]:null;choices=[];if(first)choices.push(first);while(choices.length<3&&pool.length){let c=pool.splice(Math.floor(Math.random()*pool.length),1)[0];if(!choices.includes(c))choices.push(c)}let box=document.createElement('div');box.id='cards';box.style.cssText='position:fixed;inset:0;z-index:9;background:#061014e8;display:grid;place-content:center;gap:12px;padding:24px;text-align:center';box.innerHTML='<h2>LEVEL '+level+' — CHOOSE ONE</h2>'+choices.map((c,i)=>`<button data-card="${i}" style="width:260px;padding:18px;background:#16383a;color:#eafffa;border:1px solid #75f0db;border-radius:8px"><b>${c.name}</b><br>${c.text}</button>`).join('');document.body.append(box);box.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{choices[Number(b.dataset.card)].apply();cardPicks++;box.remove();state='play'})}
function openMeta(){if(document.querySelector('#meta'))return;let box=document.createElement('div');box.id='meta';box.style.cssText='position:fixed;inset:0;z-index:10;background:#061014e8;display:grid;place-content:center;gap:10px;padding:24px;text-align:center';let render=()=>{box.innerHTML=`<h2>META UPGRADES</h2><p>${META.credits} biomatter · each rank = 5%, hard cap 25%</p>${['damage','hp','speed'].map(k=>`<button data-meta="${k}">${k.toUpperCase()} ${META[k]}/5 · cost ${META[k]+1}</button>`).join('')}<button id="metaClose">Close</button>`;box.querySelectorAll('[data-meta]').forEach(b=>b.onclick=()=>{let k=b.dataset.meta,cost=META[k]+1;if(META[k]<5&&META.credits>=cost){META.credits-=cost;META[k]++;saveMeta();render()}});box.querySelector('#metaClose').onclick=()=>box.remove()};render();document.body.append(box)}addEventListener('keydown',e=>{if(e.key.toLowerCase()==='m'&&(state==='title'||state==='dead'))openMeta()});
addEventListener('click',e=>{let b=e.target.closest&&e.target.closest('[data-card]');if(b&&choices[Number(b.dataset.card)]?.name==='Scatter Shot'&&heldWeapons.length<5)heldWeapons.push(Object.assign(copy(WEAPON),{name:'Scatter Shot',shots:3,damage:Math.round(WEAPON.damage*.65)}))},true);
(function Forge(){const owner=/^(localhost|127\.0\.0\.1|\[::1\]|)$/.test(location.hostname)||location.protocol==='file:'||location.search.includes('forge');if(!owner)return;const btn=document.createElement('button'),panel=document.createElement('section');btn.id='forgeBtn';btn.textContent='⚒';btn.title='HiVE SWARM Forge (F2)';panel.id='forge';panel.hidden=true;document.body.append(btn,panel);const fields=(obj,path)=>Object.entries(obj).filter(([,v])=>typeof v==='number'||typeof v==='string').map(([k,v])=>`<label>${k}<input data-path="${path}.${k}" value="${v}"></label>`).join('');function render(){panel.innerHTML=`<h2>⚒ HiVE SWARM FORGE</h2><p class="forgeHint">Live data only: numbers, names and colors apply immediately. Enemy behaviours remain code; this table controls every enemy, weapon, wave and drop value.</p><div class="forgeGrid"><article class="forgeCard"><h3>PLAYER</h3>${fields(EDIT.player,'player')}</article><article class="forgeCard"><h3>WORLD</h3>${fields(EDIT.world,'world')}</article><article class="forgeCard"><h3>WAVES</h3>${fields(EDIT.waves,'waves')}</article><article class="forgeCard"><h3>DROPS</h3>${fields(EDIT.drops,'drops')}</article>${EDIT.weapons.map((w,i)=>`<article class="forgeCard"><h3>WEAPON · ${w.id}</h3>${fields(w,'weapons.'+i)}</article>`).join('')}${EDIT.entities.map((e,i)=>`<article class="forgeCard"><h3>ENEMY · ${e.id}</h3>${fields(e,'entities.'+i)}<button data-delete="${i}">Delete</button></article>`).join('')}</div><div class="forgeActions"><button id="addEnemy">Add enemy row</button><button id="forgeReset">Reset shipped values</button><button id="forgeClose">Close</button></div>`;panel.querySelectorAll('input').forEach(input=>input.oninput=()=>{let target=EDIT;let bits=input.dataset.path.split('.');for(let i=0;i<bits.length-1;i++)target=target[bits[i]];let old=target[bits.at(-1)],value=typeof old==='number'?Number(input.value):input.value;if(typeof old==='number'&&!Number.isFinite(value))return;target[bits.at(-1)]=value;applyForge();persistForge()});panel.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(EDIT.entities.length>1){EDIT.entities.splice(Number(b.dataset.delete),1);applyForge();persistForge();render()}});panel.querySelector('#addEnemy').onclick=()=>{let n=EDIT.entities.length+1;EDIT.entities.push({id:'enemy.custom'+n,name:'Custom '+n,r:12,hp:30,speed:70,damage:8,color:'#c7d4d3',weight:1,dropXp:1,unlockWave:1});applyForge();persistForge();render()};panel.querySelector('#forgeReset').onclick=()=>{if(confirm('Restore shipped Forge values?')){EDIT=copy(FORGE_BASE);applyForge();persistForge();render()}};panel.querySelector('#forgeClose').onclick=()=>panel.hidden=true}function toggle(){panel.hidden=!panel.hidden;if(!panel.hidden)render()}btn.onclick=toggle;addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();toggle()}});window.__hiveSwarmForge=()=>copy(EDIT)})()
