"""Catalog HiveSwarm enemy/player sprites: dirs, frames, interior holes, angle drift."""
from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

ROOT = Path(r"D:\Dev\HiveSwarm\art_src\topdown_v1")
OUT_MD = Path(r"D:\Dev\HiveSwarm\design\SPRITE_CATALOG.md")
OUT_JSON = Path(r"D:\Dev\HiveSwarm\tools\sprite_catalog.json")
DIRS = ["e", "se", "s", "sw", "w", "nw", "n", "ne"]
STEMS = [
    "player",
    "shambler",
    "runner",
    "crawler",
    "necro_node",
    "brute",
    "armored_dead",
    "mutant_enforcer",
    "zombie_colossus",
]


def content_bbox(im: Image.Image, a_min: int = 16):
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    a = im.getchannel("A")
    bb = a.point(lambda p: 255 if p >= a_min else 0).getbbox()
    return bb


def frame_count(im: Image.Image) -> int:
    w, h = im.size
    if w >= h * 1.8:
        return max(1, round(w / h))
    return 1


def split_frames(im: Image.Image):
    n = frame_count(im)
    w, h = im.size
    fw = w // n
    return [im.crop((i * fw, 0, (i + 1) * fw, h)) for i in range(n)]


def torso_hole_pct(im: Image.Image) -> float:
    """Sample a 24% box around the opaque centroid — holes here are missing torso, not limb gaps."""
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    pix = im.load()
    w, h = im.size
    xs, ys, n = 0, 0, 0
    for y in range(h):
        for x in range(w):
            if pix[x, y][3] >= 16:
                xs += x
                ys += y
                n += 1
    if n < 20:
        return 100.0
    cx, cy = xs // n, ys // n
    rw, rh = max(6, w // 8), max(8, h // 6)
    holes = tot = 0
    for y in range(max(0, cy - rh), min(h, cy + rh)):
        for x in range(max(0, cx - rw), min(w, cx + rw)):
            tot += 1
            if pix[x, y][3] < 16:
                holes += 1
    return 100.0 * holes / tot if tot else 0.0


def interior_hole_pct(im: Image.Image) -> float:
    frames = split_frames(im)
    return max(torso_hole_pct(f) for f in frames)


def mean_rgb(im: Image.Image):
    pix = [p for p in im.convert("RGBA").getdata() if p[3] >= 16]
    if not pix:
        return (0, 0, 0)
    n = len(pix)
    return (sum(p[0] for p in pix) / n, sum(p[1] for p in pix) / n, sum(p[2] for p in pix) / n)


def color_dist(a, b):
    return ((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2) ** 0.5


def inspect(path: Path):
    if not path.exists():
        return None
    im = Image.open(path)
    bb = content_bbox(im)
    return {
        "file": path.name,
        "w": im.size[0],
        "h": im.size[1],
        "frames": frame_count(im),
        "bbox": bb,
        "hole_pct": round(interior_hole_pct(im), 1),
        "rgb": tuple(round(c, 1) for c in mean_rgb(im)),
    }


rows = []
for stem in STEMS:
    rec = {"stem": stem, "idle": {}, "walk": {}, "missing": [], "flags": []}
    base = inspect(ROOT / f"{stem}.png")
    rec["base"] = base
    if base and base["hole_pct"] >= 8:
        rec["flags"].append(f"base interior holes {base['hole_pct']}%")
    colors = []
    for d in DIRS:
        idle = inspect(ROOT / f"{stem}_{d}.png")
        walk = inspect(ROOT / f"{stem}_walk_{d}.png")
        rec["idle"][d] = idle
        rec["walk"][d] = walk
        if idle is None:
            rec["missing"].append(f"idle_{d}")
        else:
            colors.append(idle["rgb"])
            if idle["hole_pct"] >= 8:
                rec["flags"].append(f"idle_{d} holes {idle['hole_pct']}%")
        if walk is None:
            rec["missing"].append(f"walk_{d}")
        else:
            if walk["frames"] < 2:
                rec["flags"].append(f"walk_{d} only {walk['frames']} frame(s)")
            if walk["hole_pct"] >= 8:
                rec["flags"].append(f"walk_{d} holes {walk['hole_pct']}%")
    if len(colors) >= 2:
        mx = 0
        pair = None
        for i, d1 in enumerate([d for d in DIRS if rec["idle"][d]]):
            for d2 in [d for d in DIRS if rec["idle"][d]][i + 1 :]:
                dist = color_dist(rec["idle"][d1]["rgb"], rec["idle"][d2]["rgb"])
                if dist > mx:
                    mx = dist
                    pair = (d1, d2, round(dist, 1))
        rec["max_idle_color_dist"] = pair
        if pair and pair[2] >= 40:
            rec["flags"].append(f"angle palette jump {pair[0]} vs {pair[1]} Δ{pair[2]}")
    rec["ok"] = not rec["missing"] and not rec["flags"]
    rows.append(rec)

OUT_JSON.write_text(json.dumps(rows, indent=2), encoding="utf-8")

lines = [
    "# HiVE SWARM — sprite catalog",
    "",
    "Generated by `tools/catalog_sprites.py`. **Current status of every playable stem.**",
    "Live product rules live in [`../HiveSwarm.md`](../HiveSwarm.md).",
    "",
    "Need per stem: base + 8 idle dirs + 8 walk strips (2+ frames). Interior hole % is the",
    "share of near-transparent pixels in the inner 56% of the content box — that is the",
    "'transparent main body' defect.",
    "",
    "| Stem | Idle | Walk | Walk frames | Max hole % | Angle ΔRGB | Verdict |",
    "|---|---:|---:|---|---:|---:|---|",
]
for rec in rows:
    idle_n = sum(1 for v in rec["idle"].values() if v)
    walk_n = sum(1 for v in rec["walk"].values() if v)
    frames = sorted({v["frames"] for v in rec["walk"].values() if v})
    holes = [v["hole_pct"] for v in list(rec["idle"].values()) + list(rec["walk"].values()) if v]
    hole = max(holes) if holes else 0
    ang = rec.get("max_idle_color_dist")
    ang_s = f"{ang[0]}/{ang[1]} {ang[2]}" if ang else "—"
    verdict = "OK" if rec["ok"] else ("MISSING " + ",".join(rec["missing"]) if rec["missing"] else "; ".join(rec["flags"][:3]))
    lines.append(
        f"| `{rec['stem']}` | {idle_n}/8 | {walk_n}/8 | {frames} | {hole} | {ang_s} | {verdict} |"
    )

lines += ["", "## Per-stem flags", ""]
for rec in rows:
    lines.append(f"### `{rec['stem']}`")
    if rec["ok"]:
        lines.append("No flags.")
    else:
        for f in rec["missing"]:
            lines.append(f"- missing `{f}`")
        for f in rec["flags"]:
            lines.append(f"- {f}")
    lines.append("")

lines += [
    "## Import queue (Hive WAR → Swarm)",
    "",
    "| Character | Role | Views today | Next |",
    "|---|---|---|---|",
    "| Praetorian | Stage boss (Queen stays out) | Hive WAR 3/4 illustration only | 8-dir idle + walk |",
    "| Queen | later | do not import | — |",
    "",
]
OUT_MD.write_text("\n".join(lines), encoding="utf-8")
print(OUT_MD)
for rec in rows:
    print(rec["stem"], "ok" if rec["ok"] else rec["missing"] or rec["flags"][:4])
